### ISSUE TITLE
it doesnt go that high

### ISSUE THREAD

**Issue by Letrobroe** [SpyterDev/FN-Super-Jumper#3]

**Comment by SpyterDev** [comment]
As of now the cap is 19.2 meters, the cap moves in increments of 7.68m (2 walls tall). I'm working on a way to adjust the cap but first I have to fix the non-linear jump height bug (ex. 15m makes you jump 19.2) due to iterations bug (the max cap formula based on clicked 3.84m+7.68m*(x-1) but because input is checked around every 10ms by my guess and the rate has an impact on how high you go). It gets a little complicated so I have to figure out a good formula for the rate. After that, I can add a way for anyone to change the cap (because Epic Games couldn't make my life easy with a simple bug).

**Comment by Letrobroe** [comment]
Ok do that


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
